CREATE TABLE USERS
(
NAME STRING,
SURNAME STRING,
MAIL  STRING,
AGE NUMBER(2)
);

INSERT INTO USERS(NAME,SURNAME,MAIL,AGE)
            VALUES('MISHA','PEREVERTKIN','pereverkinma@gmail.com',30);
INSERT INTO USERS(NAME,SURNAME,MAIL,AGE)
            VALUES('IVAN','IVANOV','ivan.v@gmail.com',20);
INSERT INTO USERS(NAME,SURNAME,MAIL,AGE)
            VALUES('PETIA','PETROV','petia.p@gmail.com',25);
